### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#29]
**Environment**
In the root directory of this repo, run `diffenv` and paste the results below, showing your environmennt. (Install with `pip install diffenv`.)

<details><summary>Environment - Click to open</summary>
  
```yaml
# ============================================================
diffenv-version: 0.2.0
# ============================================================
git:
  # ==========================================================
  git-remote: |-
    origin      git@github.com:error-central/diffenv.git (fetch)
    origin      git@github.com:error-central/diffenv.git (push)
  # ==========================================================
  git-status: |-
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   .diffenv/config.yaml
        modified:   examples/config-small.yaml

    no changes added to commit (use "git add" and/or "git commit -a")
  # ==========================================================
  git-user-email: stan@wanderingstan.com
  # ==========================================================
  git-user-name: Stan James
  # ==========================================================
  version: git version 2.22.0
# ============================================================
os:
  # ==========================================================
  timezone: 0200
  # ==========================================================
  version: Darwin 18.7.0 x86_64
# ============================================================
php:
  # ==========================================================
  composer-show: |
    /Users/stan/code/diffenv/diffenv/../facets/php/composer-show: line 3: composer: command not found
  # ==========================================================
  composer-version: |
    /Users/stan/code/diffenv/diffenv/../facets/php/composer-version: line 2: composer: command not found
  # ==========================================================
  php-version: |-
    PHP 7.1.23 (cli) (built: Feb 22 2019 22:19:32) ( NTS )
    Copyright (c) 1997-2018 The PHP Group
    Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
# ============================================================
python:
  # ==========================================================
  pip-packages:
    astroid: 2.2.5
    autopep8: 1.4.4
    bleach: 3.1.0
    certifi: 2019.6.16
    chardet: 3.0.4
    colorama: 0.4.1
    diffenv: 0.2.0
    docutils: 0.15.2
    gitdb2: 2.0.5
    GitPython: 2.1.13
    idna: 2.8
    importlib-metadata: 0.19
    isort: 4.3.21
    lazy-object-proxy: 1.4.1
    mccabe: 0.6.1
    pip: 19.0.3
    pkginfo: 1.5.0.1
    psutil: 5.6.3
    pycodestyle: 2.5.0
    Pygments: 2.4.2
    pylint: 2.3.1
    readme-renderer: 24.0
    requests: 2.22.0
    requests-toolbelt: 0.9.1
    ruamel.yaml: 0.16.0
    ruamel.yaml.clib: 0.1.0
    setuptools: 41.0.1
    six: 1.12.0
    smmap2: 2.0.5
    tqdm: 4.33.0
    twine: 1.13.0
    typed-ast: 1.4.0
    urllib3: 1.25.3
    webencodings: 0.5.1
    wheel: 0.33.4
    wrapt: 1.11.2
    zipp: 0.5.2
  # ==========================================================
  pip3-packages:
    astroid: 2.2.5
    autopep8: 1.4.4
    bleach: 3.1.0
    certifi: 2019.6.16
    chardet: 3.0.4
    colorama: 0.4.1
    diffenv: 0.2.0
    docutils: 0.15.2
    gitdb2: 2.0.5
    GitPython: 2.1.13
    idna: 2.8
    importlib-metadata: 0.19
    isort: 4.3.21
    lazy-object-proxy: 1.4.1
    mccabe: 0.6.1
    pip: 19.0.3
    pkginfo: 1.5.0.1
    psutil: 5.6.3
    pycodestyle: 2.5.0
    Pygments: 2.4.2
    pylint: 2.3.1
    readme-renderer: 24.0
    requests: 2.22.0
    requests-toolbelt: 0.9.1
    ruamel.yaml: 0.16.0
    ruamel.yaml.clib: 0.1.0
    setuptools: 41.0.1
    six: 1.12.0
    smmap2: 2.0.5
    tqdm: 4.33.0
    twine: 1.13.0
    typed-ast: 1.4.0
    urllib3: 1.25.3
    webencodings: 0.5.1
    wheel: 0.33.4
    wrapt: 1.11.2
    zipp: 0.5.2
  # ==========================================================
  python-version: Python 3.7.3
  # ==========================================================
  python3-version: Python 3.7.3
  # ==========================================================
  virtualenv: |
  # ==========================================================
  which-python: /usr/local/opt/python/libexec/bin/python
  # ==========================================================
  which-python3: /usr/local/bin/python3
# ============================================================
shell:
  # ==========================================================
  envvars:
    Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.SUotZpHrk2/Render
    CLICOLOR: '1'
    COLORFGBG: 15;0
    COLORTERM: truecolor
    COMMAND_MODE: unix2003
    DISPLAY: /private/tmp/com.apple.launchd.CYIS8W8rHK/org.macosforge.xquartz:0
    EDITOR: sublw
    GIT_EDITOR: subl -w
    HISTTIMEFORMAT: '%Y-%m-%d_%H-%M-%S; '
    HOME: /Users/stan
    ISODATETIME: '2019-08-11 14:00:16'
    ITERM_PROFILE: Default
    ITERM_SESSION_ID: w0t0p0:CA04B2AE-1241-423A-8C94-5AE451B3C967
    LANG: en_US.UTF-8
    LC_TERMINAL: iTerm2
    LC_TERMINAL_VERSION: 3.3.0beta16
    LOGNAME: stan
    LSCOLORS: GxFxCxDxBxegedabagaced
    NVM_BIN: /Users/stan/.nvm/versions/node/v10.16.0/bin
    NVM_CD_FLAGS: ''
    NVM_DIR: /Users/stan/.nvm
    OLDPWD: /Users/stan
    PATH: /Users/stan/Library/Python/3.7/bin:/usr/local/opt/python/libexec/bin:/usr/local/opt/sqlite/bin:/Users/stan/.nvm/versions/node/v10.16.0
    PS1: \033[1;90m\]───── \h $ISODATETIME ─────\] $(git_prompt)\n\[\033[0;35m\]\w\[\033[0m\]\$
      \[\033[0;92m\]
    PS2: '| => '
    PWD: /Users/stan/code/diffenv
    SECURITYSESSIONID: 186a8
    SHELL: /bin/bash
    SHLVL: '1'
    SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.ga06oU9huP/Listeners
    TERM: xterm-color
    TERM_PROGRAM: iTerm.app
    TERM_PROGRAM_VERSION: 3.3.0beta16
    TERM_SESSION_ID: w0t0p0:CA04B2AE-1241-423A-8C94-5AE451B3C967
    TMPDIR: /var/folders/9n/2vf6_x0s79bdzphhpyk83fnr0000gn/T/
    USER: stan
    XPC_FLAGS: '0x0'
    XPC_SERVICE_NAME: '0'
    _: /usr/local/bin/diffenv
    __CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x0
    __PYVENV_LAUNCHER__: /usr/local/bin/python3
  # ==========================================================
  shell-version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18) Copyright
    (C) 2007 Free Software Foundation, Inc.
```

</details>

**Describe the bug**
A test
