### ISSUE TITLE
We filter on characters when reading from url, but not when generating diff

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#34]
We filter on characters when reading from url, but not when generating diff. Thus tests fail for me, as I have unicode character (horizontal line) in my `PS1` env var.

**Environment**
  
```yaml
# Generated by diffenv. https://github.com/error-central/diffenv

diffenv-version: 0.2.0

os:

  timezone: 0200

  version: Darwin 18.7.0 x86_64

  python-version: Python 3.7.3

  python3-version: Python 3.7.3

  virtualenv: |

  which-python: /usr/local/opt/python/libexec/bin/python

  which-python3: /usr/local/bin/python3

shell:

  envvars:
    PS1: \033[1;90m\]───── \h $ISODATETIME ─────\] $(git_prompt)\n\[\033[0;35m\]\w\[\033[0m\]\$
      \[\033[0;92m\]

  shell-version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18) Copyright
    (C) 2007 Free Software Foundation, Inc.
```
