### ISSUE TITLE
yaml comments duplicated

### ISSUE THREAD

**Issue by wanderingstan** [error-central/diffenv#7]
I'm getting two sets of all the yaml comments with the `=`s, but can't figure out from code why. It looks like `yaml_set_comment_before_after_key()` is called only once and correctly. 

As an aside, I'm not totally sure we need these anymore—the YAML is quite readable. 

```
~/code/diffenv$ diffenv
# ============================================================
# ============================================================
python:
  # ==========================================================
  # ==========================================================
  pip3-packages: astroid:2.2.5 autopep8:1.4.4 certifi:2019.6.16 chardet:3.0.4 colorama:0.4.1
    diffenv:0.1 idna:2.8 isort:4.3.21 lazy-object-proxy:1.4.1 mccabe:0.6.1 pip:19.0.3
    pycodestyle:2.5.0 pylint:2.3.1 requests:2.22.0 ruamel.yaml:0.16.0 ruamel.yaml.clib:0.1.0
    setuptools:40.8.0 six:1.12.0 typed-ast:1.4.0 urllib3:1.25.3 wheel:0.33.1 wrapt:1.11.2
  # ==========================================================
  # ==========================================================
  python-version: Python 3.7.3
  # ==========================================================
  # ==========================================================
```
